name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Run basic test
      run: |
        python -c "import app.app"

    - name: Build Docker image
      run: |
        docker build -t enterprise-ci:${{ github.run_number }} .
